name: updown_arrow_scroller
description: "A new Flutter package that help scrolling web page using keyboard arrow."
version: 0.0.4
homepage: https://github.com/KhasInfotech/updown_arrow_scroller.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:




